# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/joshua/Desktop/maya_python/shaderHelper/shaderHelper_ui/shaderHelper_base1.ui',
# licensing of '/Users/joshua/Desktop/maya_python/shaderHelper/shaderHelper_ui/shaderHelper_base1.ui' applies.
#
# Created: Thu Apr 16 22:54:42 2020
#      by: pyside2-uic  running on PySide2 5.12.5
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ShaderHelper(object):
    def setupUi(self, ShaderHelper):
        ShaderHelper.setObjectName("ShaderHelper")
        ShaderHelper.resize(444, 273)
        self.centralwidget = QtWidgets.QWidget(ShaderHelper)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.main_tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.main_tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.main_tabWidget.setTabletTracking(False)
        self.main_tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.main_tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.main_tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.main_tabWidget.setUsesScrollButtons(False)
        self.main_tabWidget.setDocumentMode(True)
        self.main_tabWidget.setTabsClosable(False)
        self.main_tabWidget.setMovable(False)
        self.main_tabWidget.setObjectName("main_tabWidget")
        self.t1_selection = QtWidgets.QWidget()
        self.t1_selection.setObjectName("t1_selection")
        self.t1_gridLayout = QtWidgets.QGridLayout(self.t1_selection)
        self.t1_gridLayout.setObjectName("t1_gridLayout")
        self.t1_line1 = QtWidgets.QFrame(self.t1_selection)
        self.t1_line1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.t1_line1.setFrameShape(QtWidgets.QFrame.HLine)
        self.t1_line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.t1_line1.setObjectName("t1_line1")
        self.t1_gridLayout.addWidget(self.t1_line1, 4, 1, 1, 2)
        self.searchSelection_checkBox = QtWidgets.QCheckBox(self.t1_selection)
        self.searchSelection_checkBox.setObjectName("searchSelection_checkBox")
        self.t1_gridLayout.addWidget(self.searchSelection_checkBox, 3, 2, 1, 1)
        self.keywords_label = QtWidgets.QLabel(self.t1_selection)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.keywords_label.setFont(font)
        self.keywords_label.setObjectName("keywords_label")
        self.t1_gridLayout.addWidget(self.keywords_label, 2, 1, 1, 1)
        self.search_lineEdit = QtWidgets.QLineEdit(self.t1_selection)
        self.search_lineEdit.setObjectName("search_lineEdit")
        self.t1_gridLayout.addWidget(self.search_lineEdit, 2, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 118, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.t1_gridLayout.addItem(spacerItem, 6, 2, 1, 1)
        self.searchBy_comboBox = QtWidgets.QComboBox(self.t1_selection)
        self.searchBy_comboBox.setObjectName("searchBy_comboBox")
        self.searchBy_comboBox.addItem("")
        self.searchBy_comboBox.addItem("")
        self.searchBy_comboBox.addItem("")
        self.t1_gridLayout.addWidget(self.searchBy_comboBox, 1, 2, 1, 1)
        self.selection_listView = QtWidgets.QListView(self.t1_selection)
        self.selection_listView.setObjectName("selection_listView")
        self.t1_gridLayout.addWidget(self.selection_listView, 1, 0, 6, 1)
        self.searchBy_label = QtWidgets.QLabel(self.t1_selection)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.searchBy_label.setFont(font)
        self.searchBy_label.setObjectName("searchBy_label")
        self.t1_gridLayout.addWidget(self.searchBy_label, 1, 1, 1, 1)
        self.searchAction_label = QtWidgets.QLabel(self.t1_selection)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.searchAction_label.setFont(font)
        self.searchAction_label.setObjectName("searchAction_label")
        self.t1_gridLayout.addWidget(self.searchAction_label, 5, 1, 1, 1)
        self.searchAction_comboBox = QtWidgets.QComboBox(self.t1_selection)
        self.searchAction_comboBox.setObjectName("searchAction_comboBox")
        self.searchAction_comboBox.addItem("")
        self.t1_gridLayout.addWidget(self.searchAction_comboBox, 5, 2, 1, 1)
        self.main_tabWidget.addTab(self.t1_selection, "")
        self.t2_conversion = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t2_conversion.sizePolicy().hasHeightForWidth())
        self.t2_conversion.setSizePolicy(sizePolicy)
        self.t2_conversion.setMinimumSize(QtCore.QSize(414, 199))
        self.t2_conversion.setObjectName("t2_conversion")
        self.t2_gridLayout = QtWidgets.QGridLayout(self.t2_conversion)
        self.t2_gridLayout.setContentsMargins(2, 5, 2, 2)
        self.t2_gridLayout.setObjectName("t2_gridLayout")
        self.t2_controls_gridLayout = QtWidgets.QGridLayout()
        self.t2_controls_gridLayout.setObjectName("t2_controls_gridLayout")
        self.convertAll_BTN = QtWidgets.QPushButton(self.t2_conversion)
        self.convertAll_BTN.setObjectName("convertAll_BTN")
        self.t2_controls_gridLayout.addWidget(self.convertAll_BTN, 1, 5, 1, 1)
        self.t2_line1 = QtWidgets.QFrame(self.t2_conversion)
        self.t2_line1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.t2_line1.setFrameShape(QtWidgets.QFrame.VLine)
        self.t2_line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.t2_line1.setObjectName("t2_line1")
        self.t2_controls_gridLayout.addWidget(self.t2_line1, 1, 4, 2, 1)
        self.convertSelection_BTN = QtWidgets.QPushButton(self.t2_conversion)
        self.convertSelection_BTN.setObjectName("convertSelection_BTN")
        self.t2_controls_gridLayout.addWidget(self.convertSelection_BTN, 1, 0, 1, 4)
        self.convTo_label = QtWidgets.QLabel(self.t2_conversion)
        self.convTo_label.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.convTo_label.setFont(font)
        self.convTo_label.setObjectName("convTo_label")
        self.t2_controls_gridLayout.addWidget(self.convTo_label, 0, 0, 1, 1)
        self.conv_radioBTNs = QtWidgets.QFrame(self.t2_conversion)
        self.conv_radioBTNs.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.conv_radioBTNs.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.conv_radioBTNs.setLineWidth(1)
        self.conv_radioBTNs.setObjectName("conv_radioBTNs")
        self.convNew_radioBTN = QtWidgets.QRadioButton(self.conv_radioBTNs)
        self.convNew_radioBTN.setGeometry(QtCore.QRect(10, 10, 131, 20))
        self.convNew_radioBTN.setChecked(True)
        self.convNew_radioBTN.setObjectName("convNew_radioBTN")
        self.convSelection_radioBTN = QtWidgets.QRadioButton(self.conv_radioBTNs)
        self.convSelection_radioBTN.setGeometry(QtCore.QRect(10, 40, 161, 20))
        self.convSelection_radioBTN.setObjectName("convSelection_radioBTN")
        self.t2_controls_gridLayout.addWidget(self.conv_radioBTNs, 2, 0, 1, 4)
        self.force_checkBox = QtWidgets.QCheckBox(self.t2_conversion)
        self.force_checkBox.setMaximumSize(QtCore.QSize(75, 16777215))
        self.force_checkBox.setObjectName("force_checkBox")
        self.t2_controls_gridLayout.addWidget(self.force_checkBox, 0, 5, 1, 1)
        self.convTo_comboBox = QtWidgets.QComboBox(self.t2_conversion)
        self.convTo_comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.convTo_comboBox.setObjectName("convTo_comboBox")
        self.convTo_comboBox.addItem("")
        self.t2_controls_gridLayout.addWidget(self.convTo_comboBox, 0, 1, 1, 4)
        self.t2_gridLayout.addLayout(self.t2_controls_gridLayout, 0, 0, 1, 1)
        self.main_tabWidget.addTab(self.t2_conversion, "")
        self.t3_editing = QtWidgets.QWidget()
        self.t3_editing.setObjectName("t3_editing")
        self.t3_gridLayout = QtWidgets.QGridLayout(self.t3_editing)
        self.t3_gridLayout.setObjectName("t3_gridLayout")
        self.editSelection_BTN = QtWidgets.QPushButton(self.t3_editing)
        self.editSelection_BTN.setObjectName("editSelection_BTN")
        self.t3_gridLayout.addWidget(self.editSelection_BTN, 0, 0, 1, 1)
        self.editAll_BTN = QtWidgets.QPushButton(self.t3_editing)
        self.editAll_BTN.setObjectName("editAll_BTN")
        self.t3_gridLayout.addWidget(self.editAll_BTN, 0, 1, 1, 1)
        self.t3_line1 = QtWidgets.QFrame(self.t3_editing)
        self.t3_line1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.t3_line1.setFrameShape(QtWidgets.QFrame.HLine)
        self.t3_line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.t3_line1.setObjectName("t3_line1")
        self.t3_gridLayout.addWidget(self.t3_line1, 1, 0, 1, 2)
        self.renameFileTextures_radioBTN = QtWidgets.QRadioButton(self.t3_editing)
        self.renameFileTextures_radioBTN.setChecked(True)
        self.renameFileTextures_radioBTN.setObjectName("renameFileTextures_radioBTN")
        self.t3_gridLayout.addWidget(self.renameFileTextures_radioBTN, 2, 0, 1, 1)
        self.changeColorSpace_radioBTN = QtWidgets.QRadioButton(self.t3_editing)
        self.changeColorSpace_radioBTN.setObjectName("changeColorSpace_radioBTN")
        self.t3_gridLayout.addWidget(self.changeColorSpace_radioBTN, 3, 0, 1, 1)
        self.colorSpace_comboBox = QtWidgets.QComboBox(self.t3_editing)
        self.colorSpace_comboBox.setEnabled(True)
        self.colorSpace_comboBox.setObjectName("colorSpace_comboBox")
        self.t3_gridLayout.addWidget(self.colorSpace_comboBox, 3, 1, 1, 1)
        self.main_tabWidget.addTab(self.t3_editing, "")
        self.gridLayout.addWidget(self.main_tabWidget, 0, 0, 1, 1)
        ShaderHelper.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 444, 22))
        self.menubar.setObjectName("menubar")
        self.help_menu = QtWidgets.QMenu(self.menubar)
        self.help_menu.setObjectName("help_menu")
        self.options_menu = QtWidgets.QMenu(self.menubar)
        self.options_menu.setObjectName("options_menu")
        ShaderHelper.setMenuBar(self.menubar)
        self.selection_help = QtWidgets.QAction(ShaderHelper)
        self.selection_help.setCheckable(False)
        self.selection_help.setObjectName("selection_help")
        self.conversion_help = QtWidgets.QAction(ShaderHelper)
        self.conversion_help.setObjectName("conversion_help")
        self.editing_help = QtWidgets.QAction(ShaderHelper)
        self.editing_help.setObjectName("editing_help")
        self.activate_verbosity = QtWidgets.QAction(ShaderHelper)
        self.activate_verbosity.setCheckable(True)
        self.activate_verbosity.setObjectName("activate_verbosity")
        self.help_menu.addAction(self.selection_help)
        self.help_menu.addAction(self.conversion_help)
        self.help_menu.addAction(self.editing_help)
        self.options_menu.addAction(self.activate_verbosity)
        self.menubar.addAction(self.help_menu.menuAction())
        self.menubar.addAction(self.options_menu.menuAction())

        self.retranslateUi(ShaderHelper)
        self.main_tabWidget.setCurrentIndex(0)
        self.searchAction_comboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(ShaderHelper)

    def retranslateUi(self, ShaderHelper):
        ShaderHelper.setWindowTitle(QtWidgets.QApplication.translate("ShaderHelper", "ShaderHelper", None, -1))
        self.searchSelection_checkBox.setText(QtWidgets.QApplication.translate("ShaderHelper", "Search selection", None, -1))
        self.keywords_label.setText(QtWidgets.QApplication.translate("ShaderHelper", "Keywords:", None, -1))
        self.search_lineEdit.setToolTip(QtWidgets.QApplication.translate("ShaderHelper", "Keywords seperated by comma.", None, -1))
        self.searchBy_comboBox.setToolTip(QtWidgets.QApplication.translate("ShaderHelper", "Search mode by which the resulting node is retrieved.", None, -1))
        self.searchBy_comboBox.setItemText(0, QtWidgets.QApplication.translate("ShaderHelper", "Nodes", None, -1))
        self.searchBy_comboBox.setItemText(1, QtWidgets.QApplication.translate("ShaderHelper", "File Textures Names", None, -1))
        self.searchBy_comboBox.setItemText(2, QtWidgets.QApplication.translate("ShaderHelper", "Colorspaces", None, -1))
        self.searchBy_label.setText(QtWidgets.QApplication.translate("ShaderHelper", "Search by:", None, -1))
        self.searchAction_label.setText(QtWidgets.QApplication.translate("ShaderHelper", "Search Action:", None, -1))
        self.searchAction_comboBox.setItemText(0, QtWidgets.QApplication.translate("ShaderHelper", "non-ACES Textures", None, -1))
        self.main_tabWidget.setTabText(self.main_tabWidget.indexOf(self.t1_selection), QtWidgets.QApplication.translate("ShaderHelper", "Selection", None, -1))
        self.convertAll_BTN.setText(QtWidgets.QApplication.translate("ShaderHelper", "Convert All", None, -1))
        self.convertSelection_BTN.setText(QtWidgets.QApplication.translate("ShaderHelper", "Convert Selection", None, -1))
        self.convTo_label.setText(QtWidgets.QApplication.translate("ShaderHelper", "Convert to:", None, -1))
        self.convNew_radioBTN.setText(QtWidgets.QApplication.translate("ShaderHelper", "convert with new", None, -1))
        self.convSelection_radioBTN.setText(QtWidgets.QApplication.translate("ShaderHelper", "convert with selection", None, -1))
        self.force_checkBox.setToolTip(QtWidgets.QApplication.translate("ShaderHelper", "Delete Source Shaders.", None, -1))
        self.force_checkBox.setText(QtWidgets.QApplication.translate("ShaderHelper", "Force", None, -1))
        self.convTo_comboBox.setItemText(0, QtWidgets.QApplication.translate("ShaderHelper", "aiStandardSurface", None, -1))
        self.main_tabWidget.setTabText(self.main_tabWidget.indexOf(self.t2_conversion), QtWidgets.QApplication.translate("ShaderHelper", "Conversion", None, -1))
        self.editSelection_BTN.setText(QtWidgets.QApplication.translate("ShaderHelper", "Edit Selection", None, -1))
        self.editAll_BTN.setText(QtWidgets.QApplication.translate("ShaderHelper", "Edit All", None, -1))
        self.renameFileTextures_radioBTN.setToolTip(QtWidgets.QApplication.translate("ShaderHelper", "Rename FileTexture Nodes to there FileTexture Names.", None, -1))
        self.renameFileTextures_radioBTN.setText(QtWidgets.QApplication.translate("ShaderHelper", "rename FileTextures", None, -1))
        self.changeColorSpace_radioBTN.setText(QtWidgets.QApplication.translate("ShaderHelper", "change Colorspace", None, -1))
        self.main_tabWidget.setTabText(self.main_tabWidget.indexOf(self.t3_editing), QtWidgets.QApplication.translate("ShaderHelper", "Editing", None, -1))
        self.help_menu.setTitle(QtWidgets.QApplication.translate("ShaderHelper", "Help", None, -1))
        self.options_menu.setTitle(QtWidgets.QApplication.translate("ShaderHelper", "Options", None, -1))
        self.selection_help.setText(QtWidgets.QApplication.translate("ShaderHelper", "Selection help", None, -1))
        self.conversion_help.setText(QtWidgets.QApplication.translate("ShaderHelper", "Conversion help", None, -1))
        self.editing_help.setText(QtWidgets.QApplication.translate("ShaderHelper", "Editing help", None, -1))
        self.activate_verbosity.setText(QtWidgets.QApplication.translate("ShaderHelper", "Activate Verbosity", None, -1))

